### ISSUE TITLE
Ribbon sends `nope` on logout while in room

### ISSUE THREAD

**Issue by mat1jaczyyy** [Proximitynow19/TETR.JS#56]
Since [TETR.IO 6.4.3](https://tetr.io/about/patchnotes/#chlog_6_4_3), logging out of a client while inside a room now causes the server to `nope` us out which takes down the entire node process with the following stack trace:

```
/srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/commands/nope.js:7
    throw new Error(reason);
          ^

Error: ribbon expired
    at default_1 (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/commands/nope.js:7:11)
    at WebSocketManager.<anonymous> (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/WebSocketManager.js:193:23)
    at Generator.next (<anonymous>)
    at /srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/WebSocketManager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/WebSocketManager.js:4:12)
    at WebSocketManager.receive (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/WebSocketManager.js:185:16)
    at WebSocket.<anonymous> (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/ws/WebSocketManager.js:139:30)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/srv/eucannon-prod/bot/node_modules/ws/lib/websocket.js:1209:20)
```

```js
const client = new tetrjs.Client();
await client.login(creds.token);

const room = await client.room.create("private");
setTimeout(() => client.logout(), 2000);
```

I have not tested this repro, but it should reproduce based off of [EU Cannon bot code](https://github.com/EUCannon/bot/blob/ca97461f369bbce65f4aeedf02243434ae3637a8/index.js#L336-L339).

**Comment by Sup3rFire** [comment]
fixed
