### ISSUE TITLE
Rate limit on fetching Tetra Channel information for players in room

### ISSUE THREAD

**Issue by mat1jaczyyy** [Proximitynow19/TETR.JS#57]
if a room has 10+ people it's possible to hit rate limit on channelApi here, which takes down the entire node process:
https://github.com/tetrjs/tetr.js/blob/226bf41a8a382e48e1c5be52494fd31f20b21c11/src/ws/commands/room.update.ts#L92-L94

```
/srv/eucannon-prod/bot/node_modules/tetr.js/dist/util/channelApi.js:34
            throw Error((yield response).error);
                  ^

Error: Rate limit exceeded! | You are doing that far too quickly.
    at /srv/eucannon-prod/bot/node_modules/tetr.js/dist/util/channelApi.js:34:19
    at Generator.next (<anonymous>)
    at fulfilled (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/util/channelApi.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mat1jaczyyy** [comment]
do you expect the newly implemented err/kick/nope handling to handle this case, allowing us to log the error and only taking down that client instead of the entire process?

**Comment by Sup3rFire** [comment]
the newly implemented err/kick/nope only emits the respective events that are sent from the server

**Comment by mat1jaczyyy** [comment]
> the newly implemented err/kick/nope only emits the respective events that are sent from the server

can you pls try catch this somehow and stall for a second or two and try again on exception?

we got a 100 entrant tournament rn and this is looking scary as hell

or maybe allow for caching the channelApi results and only fetching them once ever

**Comment by halp1** [comment]
Use the game api instead of tetr channel (no rate limit) `https://tetr.io/api/users/${userid}`

**Comment by mat1jaczyyy** [comment]
big if true, is he right

**Comment by Sup3rFire** [comment]
seems like the rate limit is a lot higher there yes

**Comment by Sup3rFire** [comment]
ill change this in a later update since using tetrchannel isnt really causing problems for now

**Comment by mat1jaczyyy** [comment]
well it didnt happen last month but it just happened again right now, luckily it's stream room so no big deal but if this were to happen mid tournament we are shitting bricks

```
2024-06-02 14:12:43.077  [Room KSQR] Replay saved! IDreplay=614 for IDmatch=811
/srv/eucannon-prod/bot/node_modules/tetr.js/dist/util/channelApi.js:35
            throw Error((yield response).error);
                  ^

Error: Rate limit exceeded! | You are doing that far too quickly.
    at /srv/eucannon-prod/bot/node_modules/tetr.js/dist/util/channelApi.js:35:19
    at Generator.next (<anonymous>)
    at fulfilled (/srv/eucannon-prod/bot/node_modules/tetr.js/dist/util/channelApi.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Sup3rFire** [comment]
ok nvm ill implement it soon then
